# -*- coding: utf-8 -*-
"""Audio SNR Simulation Tool.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-5ZTNXnOQNMAnaxGvshZQEd7joYIBdU
"""

# Install if needed
#!pip install librosa soundfile ipywidgets -q

import os
import librosa
import numpy as np
import soundfile as sf
import matplotlib.pyplot as plt

from IPython.display import display, Audio, clear_output
import ipywidgets as widgets

TARGET_SAMPLE_RATE = 16000


# ---------------- FUNCTIONS ----------------
def load_audio(audio_path, sr=TARGET_SAMPLE_RATE):
    audio, _ = librosa.load(audio_path, sr=sr)
    return audio


def adjust_noise_for_snr(clean, noise, snr_db):

    clean_power = np.mean(clean ** 2)
    noise_power = np.mean(noise ** 2)

    target_noise_power = (
        clean_power /
        (10 ** (snr_db / 10))
    )

    scaling_factor = np.sqrt(
        target_noise_power / noise_power
    )

    adjusted_noise = noise * scaling_factor

    return adjusted_noise


def mix_audio(clean_audio, noise_audio, snr_db):

    # Match lengths
    if len(noise_audio) < len(clean_audio):

        repeat_count = int(
            np.ceil(
                len(clean_audio) /
                len(noise_audio)
            )
        )

        noise_audio = np.tile(
            noise_audio,
            repeat_count
        )

    noise_audio = noise_audio[
        :len(clean_audio)
    ]

    adjusted_noise = adjust_noise_for_snr(
        clean_audio,
        noise_audio,
        snr_db
    )

    mixed_audio = (
        clean_audio +
        adjusted_noise
    )

    mixed_audio = (
        mixed_audio /
        np.max(np.abs(mixed_audio))
    )

    return mixed_audio, adjusted_noise


def visualize_for_non_tech(snr_db):

    plt.figure(figsize=(10, 4))

    voice_strength = max(
        1,
        10 + snr_db
    )

    noise_strength = max(
        1,
        10 - snr_db
    )

    labels = [
        "Voice",
        "Noise"
    ]

    values = [
        voice_strength,
        noise_strength
    ]

    plt.bar(labels, values)

    plt.title(
        f"Understanding SNR ({snr_db} dB)"
    )

    if snr_db < 0:
        explanation = (
            "Noise is stronger.\n"
            "Hard to hear speaker."
        )

    elif snr_db == 0:
        explanation = (
            "Voice and noise\n"
            "are balanced."
        )

    else:
        explanation = (
            "Voice is stronger.\n"
            "Easy to hear speaker."
        )

    plt.figtext(
        0.5,
        -0.15,
        explanation,
        ha="center",
        fontsize=12
    )

    plt.show()


# ---------------- UI ----------------
clean_upload = widgets.FileUpload(
    accept=".wav",
    multiple=False,
    description="Upload Clean Audio"
)

noise_upload = widgets.FileUpload(
    accept=".wav",
    multiple=False,
    description="Upload Noise Audio"
)

snr_slider = widgets.IntSlider(
    value=-10,
    min=-40,
    max=40,
    step=1,
    description="SNR dB"
)

generate_button = widgets.Button(
    description="Generate Audio",
    button_style="success"
)

output = widgets.Output()


# ---------------- BUTTON ACTION ----------------
def on_generate_clicked(b):

    with output:

        clear_output()

        if not clean_upload.value:
            print("Upload clean audio")
            return

        if not noise_upload.value:
            print("Upload noise audio")
            return

        # Save uploaded files
        clean_name = list(
            clean_upload.value.keys()
        )[0]

        noise_name = list(
            noise_upload.value.keys()
        )[0]

        with open(clean_name, "wb") as f:
            f.write(
                clean_upload.value[
                    clean_name
                ]["content"]
            )

        with open(noise_name, "wb") as f:
            f.write(
                noise_upload.value[
                    noise_name
                ]["content"]
            )

        # Load audio
        clean_audio = load_audio(
            clean_name
        )

        noise_audio = load_audio(
            noise_name
        )

        # Mix
        mixed_audio, _ = mix_audio(
            clean_audio,
            noise_audio,
            snr_slider.value
        )

        # Save
        output_path = (
            f"mixed_"
            f"{snr_slider.value}dB.wav"
        )

        sf.write(
            output_path,
            mixed_audio,
            TARGET_SAMPLE_RATE
        )

        # ---------------- DISPLAY ----------------
        print(" Clean Audio")
        display(
            Audio(
                clean_audio,
                rate=TARGET_SAMPLE_RATE
            )
        )

        print(" Noise Audio")
        display(
            Audio(
                noise_audio,
                rate=TARGET_SAMPLE_RATE
            )
        )

        print(
            f" Final Mixed Audio "
            f"({snr_slider.value} dB)"
        )

        display(
            Audio(
                mixed_audio,
                rate=TARGET_SAMPLE_RATE
            )
        )

        # Non-tech visual
        visualize_for_non_tech(
            snr_slider.value
        )


generate_button.on_click(
    on_generate_clicked
)

display(
    clean_upload,
    noise_upload,
    snr_slider,
    generate_button,
    output
)

"""**Audio SNR Simulation Tool**

This tool generates realistic noisy audio by mixing clean speech with background noise at adjustable SNR levels (-40 to +40 dB). It helps simulate different real-world acoustic conditions and evaluate how noise affects speech clarity.
Users can upload audio, set SNR, and instantly hear and visualize the difference between clean, noisy, and final mixed audio in an easy-to-understand format for both technical and non-technical stakeholders.
"""